import { useCallback, useEffect, useState, type ReactNode } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router';
import { ArrowLeft, Check, Copy } from 'lucide-react';
import {
  DISPLAY_NAME_MAX_LENGTH,
  defaultDisplayName,
  type AccessResponse,
  type Device,
  type Player,
} from '../shared/api';
import { isCurrentIdentityResponse, request } from './data/api';
import {
  Button,
  defaultDeviceName,
  Field,
  Loading,
  messageOf,
  Notice,
  Placeholder,
  useApp,
  useReveal,
} from './ui';
import { InstallApp } from './pwa-install';
import { PairingCode } from './pairing';
import { OfflineSettings } from './pwa-ui';

function RecoveryCode({ code }: { code: string }) {
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState('');
  return (
    <div className="recovery-code-block">
      <p>
        <strong>Save this recovery code somewhere safe.</strong> It is shown only here and gives
        access to your prices.
      </p>
      <code className="secret-code">{code}</code>
      <Button
        secondary
        onClick={() => {
          void navigator.clipboard
            .writeText(code)
            .then(() => setCopied(true))
            .catch(() => setError('Select the code above to copy it manually.'));
        }}
      >
        {copied ? <Check size={16} /> : <Copy size={16} />}
        {copied ? 'Copied' : 'Copy code'}
      </Button>
      {error && <Notice>{error}</Notice>}
    </div>
  );
}

function Profile() {
  const { session, adopt } = useApp();
  const [displayName, setDisplayName] = useState(session?.player.displayName ?? '');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [saved, setSaved] = useState(false);
  async function save(event: React.SubmitEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!session) return;
    const form = new FormData(event.currentTarget);
    setBusy(true);
    setError('');
    setSaved(false);
    try {
      const result = await request<{ player: Player }>('/profile', {
        method: 'PATCH',
        body: { displayName: form.get('displayName') },
      });
      if (!isCurrentIdentityResponse(result))
        throw new Error('Your profile changed. Please try again.');
      await adopt({ ...session, player: result.player });
      setDisplayName(result.player.displayName);
      setSaved(true);
    } catch (error) {
      setError(messageOf(error));
    } finally {
      setBusy(false);
    }
  }
  if (!session) return null;
  return (
    <section className="settings-section" id="profile">
      <h2>Profile</h2>
      <form
        onSubmit={(event) => {
          void save(event);
        }}
        onChange={() => setSaved(false)}
      >
        <Field
          label="Display name"
          name="displayName"
          value={displayName}
          onChange={(event) => setDisplayName(event.target.value)}
          disabled={busy}
          maxLength={DISPLAY_NAME_MAX_LENGTH}
          autoComplete="nickname"
          hint={`Up to ${DISPLAY_NAME_MAX_LENGTH} characters. Leave it empty to go by ${defaultDisplayName(session.player.friendCode)}.`}
        />
        <Field
          label="Friend code"
          value={session.player.friendCode ?? ''}
          readOnly
          hint="Generated by Turnip Tycoon. This code stays the same when you change your name."
        />
        {error && <Notice>{error}</Notice>}
        <div className="button-row">
          <Button busy={busy} type="submit">
            Save name
          </Button>
          {saved && (
            <span className="saved-message" role="status">
              Name saved
            </span>
          )}
        </div>
      </form>
    </section>
  );
}

function Devices({ refreshCount }: { refreshCount: number }) {
  const [devices, setDevices] = useState<Device[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [busyId, setBusyId] = useState('');
  const [confirmId, setConfirmId] = useState('');
  const [removed, setRemoved] = useState('');
  const reveal = useReveal(loading && !devices.length);
  const refresh = useCallback(async () => {
    setLoading(true);
    setError('');
    try {
      setDevices((await request<{ devices: Device[] }>('/devices')).devices);
    } catch (error) {
      setError(messageOf(error));
    } finally {
      setLoading(false);
    }
  }, []);
  useEffect(() => {
    void refresh();
  }, [refresh, refreshCount]);
  async function remove(device: Device) {
    setBusyId(device.id);
    setError('');
    try {
      await request(`/devices/${device.id}`, { method: 'DELETE' });
      setDevices((items) => items.filter((item) => item.id !== device.id));
      setConfirmId('');
      setRemoved(`${device.name} disconnected.`);
    } catch (error) {
      setError(messageOf(error));
    } finally {
      setBusyId('');
    }
  }
  return (
    <>
      <h3>Connected devices</h3>
      {loading && !devices.length ? (
        <Loading label="Loading devices…">
          <ul className="device-list">
            {[0, 1].map((row) => (
              <li key={row}>
                <div className="device-row">
                  <div>
                    <strong>
                      <Placeholder width="7em" />
                    </strong>
                    <span className="hint">
                      <Placeholder width="11em" />
                    </span>
                  </div>
                </div>
              </li>
            ))}
          </ul>
        </Loading>
      ) : (
        <ul className={`device-list ${reveal}`}>
          {devices.map((device) => (
            <li key={device.id}>
              <div className="device-row">
                <div>
                  <strong>{device.name}</strong>
                  <span className="hint">
                    {device.current
                      ? 'This device'
                      : `Connected ${new Date(device.createdAt).toLocaleDateString()}`}
                  </span>
                </div>
                {!device.current && (
                  <button
                    type="button"
                    className="text-button"
                    onClick={() => setConfirmId(device.id)}
                  >
                    Disconnect
                  </button>
                )}
              </div>
              {confirmId === device.id && (
                <div className="inline-confirm">
                  <p>Disconnect {device.name}? You can connect it again later.</p>
                  <div className="button-row">
                    <Button secondary onClick={() => setConfirmId('')}>
                      Cancel
                    </Button>
                    <Button
                      busy={busyId === device.id}
                      onClick={() => {
                        void remove(device);
                      }}
                    >
                      Disconnect device
                    </Button>
                  </div>
                </div>
              )}
            </li>
          ))}
        </ul>
      )}
      {error && (
        <>
          <Notice>{error}</Notice>
          <Button
            secondary
            onClick={() => {
              void refresh();
            }}
          >
            Retry devices
          </Button>
        </>
      )}
      {removed && (
        <p className="saved-message" role="status">
          {removed}
        </p>
      )}
    </>
  );
}

function ApproveDevice({ onApproved }: { onApproved: () => void }) {
  const [searchParams, setSearchParams] = useSearchParams();
  const [code, setCode] = useState(searchParams.get('pair') ?? '');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState(false);
  async function approve(event: React.SubmitEvent<HTMLFormElement>) {
    event.preventDefault();
    setBusy(true);
    setError('');
    setSuccess(false);
    try {
      await request('/pairing/approve', { method: 'POST', body: { code } });
      setSuccess(true);
      setCode('');
      onApproved();
      if (searchParams.has('pair')) {
        const next = new URLSearchParams(searchParams);
        next.delete('pair');
        void setSearchParams(next, { replace: true });
      }
    } catch (error) {
      setError(messageOf(error));
    } finally {
      setBusy(false);
    }
  }
  return (
    <details
      className="settings-details"
      open={searchParams.has('pair') || success || undefined}
      id="approve"
    >
      <summary>Approve another device</summary>
      <p>
        On the new device, open Settings → Connect this device to an existing profile. Enter its
        connection code here.
      </p>
      <form
        onSubmit={(event) => {
          void approve(event);
        }}
      >
        <Field
          label="Connection code"
          name="pairingCode"
          value={code}
          onChange={(event) => {
            setCode(event.target.value);
            setSuccess(false);
          }}
          required
          maxLength={40}
          autoComplete="off"
          spellCheck={false}
        />
        {error && <Notice>{error}</Notice>}
        {success && (
          <Notice success>Approved. On the new device, select “Finish connecting”.</Notice>
        )}
        <Button busy={busy} type="submit">
          Approve device
        </Button>
      </form>
    </details>
  );
}

function RecoverySettings() {
  const { session, adopt } = useApp();
  const [code, setCode] = useState('');
  const [confirming, setConfirming] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  async function create() {
    if (!session) return;
    setBusy(true);
    setError('');
    try {
      const result = await request<{ recoveryCode: string }>('/recovery/rotate', {
        method: 'POST',
        body: {},
      });
      if (!isCurrentIdentityResponse(result))
        throw new Error('Your profile changed. Please try again.');
      await adopt({ ...session, hasRecoveryCode: true });
      setCode(result.recoveryCode);
      setConfirming(false);
    } catch (error) {
      setError(messageOf(error));
    } finally {
      setBusy(false);
    }
  }
  return (
    <section className="settings-section" id="recovery">
      <h2>Recovery code</h2>
      <p>
        Create a code to get your prices back if you lose access to this device. Keep it somewhere
        private.
      </p>
      {code && <RecoveryCode code={code} />}
      {error && <Notice>{error}</Notice>}
      {confirming ? (
        <div className="inline-confirm">
          <p>
            Your previous recovery code will stop working. Connected devices will stay connected.
          </p>
          <div className="button-row">
            <Button secondary onClick={() => setConfirming(false)}>
              Cancel
            </Button>
            <Button
              busy={busy}
              onClick={() => {
                void create();
              }}
            >
              Replace recovery code
            </Button>
          </div>
        </div>
      ) : (
        <Button
          secondary
          busy={busy}
          onClick={() => {
            if (session?.hasRecoveryCode) setConfirming(true);
            else void create();
          }}
        >
          {session?.hasRecoveryCode ? 'Replace recovery code' : 'Create recovery code'}
        </Button>
      )}
    </section>
  );
}

export function Settings() {
  const identity = useApp();
  const [refreshCount, setRefreshCount] = useState(0);
  return (
    <main className="page narrow-page" id="main-content">
      <div className="page-heading">
        <h1>Settings</h1>
      </div>
      {identity.session && identity.error && <Notice>{identity.error}</Notice>}
      {identity.session ? (
        <>
          <Profile />
          <section className="settings-section" id="devices">
            <h2>Devices</h2>
            <Devices refreshCount={refreshCount} />
            <ApproveDevice onApproved={() => setRefreshCount((count) => count + 1)} />
            <div className="access-links">
              <Link to="/connect">Connect this device to an existing profile</Link>
              <Link to="/recover">Use a recovery code</Link>
            </div>
          </section>
          <RecoverySettings />
        </>
      ) : (
        <>
          <p>
            {identity.status === 'connecting'
              ? 'Connecting your profile… You can already enter prices.'
              : 'Your profile is temporarily unavailable. Prices can still be entered on this device.'}
          </p>
          {identity.error && <Notice>{identity.error}</Notice>}
          <div className="button-row">
            <Button
              secondary
              onClick={() => {
                void (identity.creationInterrupted
                  ? identity.restartInterruptedCreation()
                  : identity.retry());
              }}
            >
              {identity.creationInterrupted ? 'Start a new profile' : 'Retry connection'}
            </Button>
            <Link to="/">Back to prices</Link>
          </div>
          <div className="access-links">
            <Link to="/connect">Connect an existing profile</Link>
            <Link to="/recover">Use a recovery code</Link>
          </div>
        </>
      )}
      <InstallApp />
      <OfflineSettings />
    </main>
  );
}

function AccessPage({ title, children }: { title: string; children: ReactNode }) {
  return (
    <main id="main-content" className="page narrow-page">
      <Link className="back-link" to="/settings">
        <ArrowLeft size={16} /> Settings
      </Link>
      <h1>{title}</h1>
      {children}
    </main>
  );
}

export function Connect() {
  const navigate = useNavigate();
  const [deviceName, setDeviceName] = useState<string | null>(null);
  return (
    <AccessPage title="Connect an existing profile">
      <p>
        Use another connected device to bring that profile’s prices here. Switching profiles does
        not merge prices.
      </p>
      {deviceName === null ? (
        <form
          className="access-form"
          onSubmit={(event) => {
            event.preventDefault();
            const value = new FormData(event.currentTarget).get('deviceName');
            setDeviceName(typeof value === 'string' ? value : defaultDeviceName());
          }}
        >
          <Field
            label="This device’s name"
            name="deviceName"
            defaultValue={defaultDeviceName()}
            required
            maxLength={60}
          />
          <Button type="submit">Get a connection code</Button>
        </form>
      ) : (
        <>
          <p>On your connected device, open Settings and choose “Approve another device”.</p>
          <PairingCode
            deviceName={deviceName}
            onConnected={() => {
              void navigate('/');
            }}
          />
        </>
      )}
      <p className="access-alternative">
        <Link to="/recover">Use a recovery code instead</Link>
      </p>
    </AccessPage>
  );
}

export function Recover() {
  const { adopt, beginIdentityChange } = useApp();
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [newCode, setNewCode] = useState('');
  async function recover(event: React.SubmitEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    setBusy(true);
    setError('');
    try {
      beginIdentityChange();
      const result = await request<AccessResponse>('/recovery', {
        method: 'POST',
        body: { code: form.get('code'), deviceName: form.get('deviceName') },
      });
      await adopt(result);
      setNewCode(result.recoveryCode);
    } catch (error) {
      setError(messageOf(error));
    } finally {
      setBusy(false);
    }
  }
  return (
    <AccessPage title={newCode ? 'Profile recovered' : 'Use a recovery code'}>
      {newCode ? (
        <>
          <Notice success>
            Your profile is connected. Your old recovery code has been replaced.
          </Notice>
          <RecoveryCode code={newCode} />
          <Link className="button" to="/">
            Return to prices
          </Link>
        </>
      ) : (
        <>
          <p>
            Enter your saved recovery code. Switching profiles does not merge prices. Recovery
            replaces the code with a new one.
          </p>
          <form
            className="access-form"
            onSubmit={(event) => {
              void recover(event);
            }}
          >
            <Field
              label="Recovery code"
              name="code"
              required
              maxLength={80}
              autoComplete="off"
              spellCheck={false}
            />
            <Field
              label="This device’s name"
              name="deviceName"
              required
              maxLength={60}
              defaultValue={defaultDeviceName()}
            />
            {error && <Notice>{error}</Notice>}
            <Button busy={busy} type="submit">
              Recover profile
            </Button>
          </form>
          <p className="access-alternative">
            <Link to="/connect">Connect using another device instead</Link>
          </p>
        </>
      )}
    </AccessPage>
  );
}
