import { useCallback, useEffect, useState, type ReactNode } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router';
import { ArrowLeft, Check, Copy } from 'lucide-react';
import { i18n } from '@lingui/core';
import { t } from '@lingui/core/macro';
import { Trans, useLingui } from '@lingui/react/macro';
import {
  DISPLAY_NAME_MAX_LENGTH,
  defaultDisplayName,
  type AccessResponse,
  type Device,
  type Player,
} from '../shared/api';
import { isCurrentIdentityResponse, request } from './data/api';
import { chooseLocale, LANGUAGES } from './i18n';
import {
  Button,
  defaultDeviceName,
  Field,
  Loading,
  messageOf,
  Notice,
  Placeholder,
  useApp,
  useReveal,
} from './ui';
import { PairingCode } from './pairing';
import { ProfileDataSettings } from './profile-data';

function RecoveryCode({ code }: { code: string }) {
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState('');
  return (
    <div className="recovery-code-block">
      <p>
        <Trans>
          <strong>Save this recovery code somewhere safe.</strong> It is shown only here and gives
          access to your prices.
        </Trans>
      </p>
      <code className="secret-code">{code}</code>
      <Button
        secondary
        onClick={() => {
          void navigator.clipboard
            .writeText(code)
            .then(() => setCopied(true))
            .catch(() => setError(t`Select the code above to copy it manually.`));
        }}
      >
        {copied ? <Check size={16} /> : <Copy size={16} />}
        {copied ? t`Copied` : t`Copy code`}
      </Button>
      {error && <Notice>{error}</Notice>}
    </div>
  );
}

function Profile() {
  const { session, adopt } = useApp();
  const [displayName, setDisplayName] = useState(session?.player.displayName ?? '');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [saved, setSaved] = useState(false);
  async function save(event: React.SubmitEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!session) return;
    const form = new FormData(event.currentTarget);
    setBusy(true);
    setError('');
    setSaved(false);
    try {
      const result = await request<{ player: Player }>('/profile', {
        method: 'PATCH',
        body: { displayName: form.get('displayName') },
      });
      if (!isCurrentIdentityResponse(result))
        throw new Error(t`Your profile changed. Please try again.`);
      await adopt({ ...session, player: result.player });
      setDisplayName(result.player.displayName);
      setSaved(true);
    } catch (error) {
      setError(messageOf(error));
    } finally {
      setBusy(false);
    }
  }
  if (!session) return null;
  const maxLength = DISPLAY_NAME_MAX_LENGTH;
  const defaultName = defaultDisplayName(session.player.friendCode);
  return (
    <section className="settings-section" id="profile">
      <h2>
        <Trans>Profile</Trans>
      </h2>
      <form
        onSubmit={(event) => {
          void save(event);
        }}
        onChange={() => setSaved(false)}
      >
        <Field
          label={t`Display name`}
          name="displayName"
          value={displayName}
          onChange={(event) => setDisplayName(event.target.value)}
          disabled={busy}
          maxLength={DISPLAY_NAME_MAX_LENGTH}
          autoComplete="nickname"
          hint={t`Up to ${maxLength} characters. Leave it empty to go by ${defaultName}.`}
        />
        <Field
          label={t`Friend code`}
          value={session.player.friendCode ?? ''}
          readOnly
          hint={t`Generated by Turnip Tycoon. This code stays the same when you change your name.`}
        />
        {error && <Notice>{error}</Notice>}
        <div className="button-row">
          <Button busy={busy} type="submit">
            <Trans>Save name</Trans>
          </Button>
          {saved && (
            <span className="saved-message" role="status">
              <Trans>Name saved</Trans>
            </span>
          )}
        </div>
      </form>
    </section>
  );
}

function Devices({ refreshCount }: { refreshCount: number }) {
  const [devices, setDevices] = useState<Device[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [busyId, setBusyId] = useState('');
  const [confirmId, setConfirmId] = useState('');
  const [removed, setRemoved] = useState('');
  const reveal = useReveal(loading && !devices.length);
  const refresh = useCallback(async () => {
    setLoading(true);
    setError('');
    try {
      setDevices((await request<{ devices: Device[] }>('/devices')).devices);
    } catch (error) {
      setError(messageOf(error));
    } finally {
      setLoading(false);
    }
  }, []);
  useEffect(() => {
    void refresh();
  }, [refresh, refreshCount]);
  async function remove(device: Device) {
    setBusyId(device.id);
    setError('');
    try {
      await request(`/devices/${device.id}`, { method: 'DELETE' });
      setDevices((items) => items.filter((item) => item.id !== device.id));
      setConfirmId('');
      const name = device.name;
      setRemoved(t`${name} disconnected.`);
    } catch (error) {
      setError(messageOf(error));
    } finally {
      setBusyId('');
    }
  }
  return (
    <>
      <h3>
        <Trans>Connected devices</Trans>
      </h3>
      {loading && !devices.length ? (
        <Loading label={t`Loading devices…`}>
          <ul className="device-list">
            {[0, 1].map((row) => (
              <li key={row}>
                <div className="device-row">
                  <div>
                    <strong>
                      <Placeholder width="7em" />
                    </strong>
                    <span className="hint">
                      <Placeholder width="11em" />
                    </span>
                  </div>
                </div>
              </li>
            ))}
          </ul>
        </Loading>
      ) : (
        <ul className={`device-list ${reveal}`}>
          {devices.map((device) => {
            const name = device.name;
            const connected = i18n.date(new Date(device.createdAt));
            return (
              <li key={device.id}>
                <div className="device-row">
                  <div>
                    <strong>{device.name}</strong>
                    <span className="hint">
                      {device.current ? t`This device` : t`Connected ${connected}`}
                    </span>
                  </div>
                  {!device.current && (
                    <button
                      type="button"
                      className="text-button"
                      onClick={() => setConfirmId(device.id)}
                    >
                      <Trans>Disconnect</Trans>
                    </button>
                  )}
                </div>
                {confirmId === device.id && (
                  <div className="inline-confirm">
                    <p>
                      <Trans>Disconnect {name}? You can connect it again later.</Trans>
                    </p>
                    <div className="button-row">
                      <Button secondary onClick={() => setConfirmId('')}>
                        <Trans>Cancel</Trans>
                      </Button>
                      <Button
                        busy={busyId === device.id}
                        onClick={() => {
                          void remove(device);
                        }}
                      >
                        <Trans>Disconnect device</Trans>
                      </Button>
                    </div>
                  </div>
                )}
              </li>
            );
          })}
        </ul>
      )}
      {error && (
        <>
          <Notice>{error}</Notice>
          <Button
            secondary
            onClick={() => {
              void refresh();
            }}
          >
            <Trans>Retry devices</Trans>
          </Button>
        </>
      )}
      {removed && (
        <p className="saved-message" role="status">
          {removed}
        </p>
      )}
    </>
  );
}

function ApproveDevice({ onApproved }: { onApproved: () => void }) {
  const [searchParams, setSearchParams] = useSearchParams();
  const [code, setCode] = useState(searchParams.get('pair') ?? '');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState(false);
  async function approve(event: React.SubmitEvent<HTMLFormElement>) {
    event.preventDefault();
    setBusy(true);
    setError('');
    setSuccess(false);
    try {
      await request('/pairing/approve', { method: 'POST', body: { code } });
      setSuccess(true);
      setCode('');
      onApproved();
      if (searchParams.has('pair')) {
        const next = new URLSearchParams(searchParams);
        next.delete('pair');
        void setSearchParams(next, { replace: true });
      }
    } catch (error) {
      setError(messageOf(error));
    } finally {
      setBusy(false);
    }
  }
  return (
    <details
      className="settings-details"
      open={searchParams.has('pair') || success || undefined}
      id="approve"
    >
      <summary>
        <Trans>Approve another device</Trans>
      </summary>
      <p>
        <Trans>
          On the new device, open Settings → Connect this device to an existing profile. Enter its
          connection code here.
        </Trans>
      </p>
      <form
        onSubmit={(event) => {
          void approve(event);
        }}
      >
        <Field
          label={t`Connection code`}
          name="pairingCode"
          value={code}
          onChange={(event) => {
            setCode(event.target.value);
            setSuccess(false);
          }}
          required
          maxLength={40}
          autoComplete="off"
          spellCheck={false}
        />
        {error && <Notice>{error}</Notice>}
        {success && (
          <Notice success>
            <Trans>Approved. On the new device, select “Finish connecting”.</Trans>
          </Notice>
        )}
        <Button busy={busy} type="submit">
          <Trans>Approve device</Trans>
        </Button>
      </form>
    </details>
  );
}

function RecoverySettings() {
  const { session, adopt } = useApp();
  const [code, setCode] = useState('');
  const [confirming, setConfirming] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  async function create() {
    if (!session) return;
    setBusy(true);
    setError('');
    try {
      const result = await request<{ recoveryCode: string }>('/recovery/rotate', {
        method: 'POST',
        body: {},
      });
      if (!isCurrentIdentityResponse(result))
        throw new Error(t`Your profile changed. Please try again.`);
      await adopt({ ...session, hasRecoveryCode: true });
      setCode(result.recoveryCode);
      setConfirming(false);
    } catch (error) {
      setError(messageOf(error));
    } finally {
      setBusy(false);
    }
  }
  return (
    <section className="settings-section" id="recovery">
      <h2>
        <Trans>Recovery code</Trans>
      </h2>
      <p>
        <Trans>
          Create a code to get your prices back if you lose access to this device. Keep it somewhere
          private.
        </Trans>
      </p>
      {code && <RecoveryCode code={code} />}
      {error && <Notice>{error}</Notice>}
      {confirming ? (
        <div className="inline-confirm">
          <p>
            <Trans>
              Your previous recovery code will stop working. Connected devices will stay connected.
            </Trans>
          </p>
          <div className="button-row">
            <Button secondary onClick={() => setConfirming(false)}>
              <Trans>Cancel</Trans>
            </Button>
            <Button
              busy={busy}
              onClick={() => {
                void create();
              }}
            >
              <Trans>Replace recovery code</Trans>
            </Button>
          </div>
        </div>
      ) : (
        <Button
          secondary
          busy={busy}
          onClick={() => {
            if (session?.hasRecoveryCode) setConfirming(true);
            else void create();
          }}
        >
          {session?.hasRecoveryCode ? t`Replace recovery code` : t`Create recovery code`}
        </Button>
      )}
    </section>
  );
}

/** Applies straight away on this device and is remembered for next time. */
function LanguageSettings() {
  const { i18n } = useLingui();
  const [changing, setChanging] = useState(false);
  const current = LANGUAGES.find((language) => language.locale === i18n.locale);
  return (
    <section className="settings-section" id="language">
      <h2>
        <Trans>Language</Trans>
      </h2>
      <div className="field">
        <label htmlFor="language-choice">
          <Trans>Show Turnip Tycoon in</Trans>
        </label>
        <select
          id="language-choice"
          value={i18n.locale}
          disabled={changing}
          onChange={(event) => {
            setChanging(true);
            void chooseLocale(event.target.value).finally(() => setChanging(false));
          }}
        >
          {LANGUAGES.map((language) => (
            <option key={language.locale} value={language.locale} lang={language.locale}>
              {language.name}
            </option>
          ))}
        </select>
      </div>
      {current?.unreviewed && (
        <p className="hint">
          <Trans>
            This translation was made by machine and hasn’t been checked by players yet, so some
            wording may be off.
          </Trans>
        </p>
      )}
    </section>
  );
}

export function Settings() {
  const identity = useApp();
  const [refreshCount, setRefreshCount] = useState(0);
  return (
    <main className="page narrow-page" id="main-content">
      <div className="page-heading">
        <h1>
          <Trans>Settings</Trans>
        </h1>
      </div>
      {identity.session && identity.error && <Notice>{identity.error}</Notice>}
      <LanguageSettings />
      {identity.session ? (
        <>
          <Profile />
          <section className="settings-section" id="devices">
            <h2>
              <Trans>Devices</Trans>
            </h2>
            <Devices refreshCount={refreshCount} />
            <ApproveDevice onApproved={() => setRefreshCount((count) => count + 1)} />
            <div className="access-links">
              <Link to="/connect">
                <Trans>Connect this device to an existing profile</Trans>
              </Link>
              <Link to="/recover">
                <Trans>Use a recovery code</Trans>
              </Link>
            </div>
          </section>
          <RecoverySettings />
          <ProfileDataSettings />
        </>
      ) : (
        <>
          <p>
            {identity.status === 'connecting'
              ? t`Connecting your profile… You can already enter prices.`
              : t`Your profile is temporarily unavailable. Prices can still be entered on this device.`}
          </p>
          {identity.error && <Notice>{identity.error}</Notice>}
          <div className="button-row">
            <Button
              secondary
              onClick={() => {
                void (identity.creationInterrupted
                  ? identity.restartInterruptedCreation()
                  : identity.retry());
              }}
            >
              {identity.creationInterrupted ? t`Start a new profile` : t`Retry connection`}
            </Button>
            <Link to="/">
              <Trans>Back to prices</Trans>
            </Link>
          </div>
          <div className="access-links">
            <Link to="/connect">
              <Trans>Connect an existing profile</Trans>
            </Link>
            <Link to="/recover">
              <Trans>Use a recovery code</Trans>
            </Link>
          </div>
        </>
      )}
    </main>
  );
}

function AccessPage({ title, children }: { title: string; children: ReactNode }) {
  return (
    <main id="main-content" className="page narrow-page">
      <Link className="back-link" to="/settings">
        <ArrowLeft size={16} /> <Trans>Settings</Trans>
      </Link>
      <h1>{title}</h1>
      {children}
    </main>
  );
}

export function Connect() {
  const navigate = useNavigate();
  const [deviceName, setDeviceName] = useState<string | null>(null);
  return (
    <AccessPage title={t`Connect an existing profile`}>
      <p>
        <Trans>
          Use another connected device to bring that profile’s prices here. Switching profiles does
          not merge prices.
        </Trans>
      </p>
      {deviceName === null ? (
        <form
          className="access-form"
          onSubmit={(event) => {
            event.preventDefault();
            const value = new FormData(event.currentTarget).get('deviceName');
            setDeviceName(typeof value === 'string' ? value : defaultDeviceName());
          }}
        >
          <Field
            label={t`This device’s name`}
            name="deviceName"
            defaultValue={defaultDeviceName()}
            required
            maxLength={60}
          />
          <Button type="submit">
            <Trans>Get a connection code</Trans>
          </Button>
        </form>
      ) : (
        <>
          <p>
            <Trans>
              On your connected device, open Settings and choose “Approve another device”.
            </Trans>
          </p>
          <PairingCode
            deviceName={deviceName}
            onConnected={() => {
              void navigate('/');
            }}
          />
        </>
      )}
      <p className="access-alternative">
        <Link to="/recover">
          <Trans>Use a recovery code instead</Trans>
        </Link>
      </p>
    </AccessPage>
  );
}

export function Recover() {
  const { adopt, beginIdentityChange } = useApp();
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [newCode, setNewCode] = useState('');
  async function recover(event: React.SubmitEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    setBusy(true);
    setError('');
    try {
      beginIdentityChange();
      const result = await request<AccessResponse>('/recovery', {
        method: 'POST',
        body: { code: form.get('code'), deviceName: form.get('deviceName') },
      });
      await adopt(result);
      setNewCode(result.recoveryCode);
    } catch (error) {
      setError(messageOf(error));
    } finally {
      setBusy(false);
    }
  }
  return (
    <AccessPage title={newCode ? t`Profile recovered` : t`Use a recovery code`}>
      {newCode ? (
        <>
          <Notice success>
            <Trans>Your profile is connected. Your old recovery code has been replaced.</Trans>
          </Notice>
          <RecoveryCode code={newCode} />
          <Link className="button" to="/">
            <Trans>Return to prices</Trans>
          </Link>
        </>
      ) : (
        <>
          <p>
            <Trans>
              Enter your saved recovery code. Switching profiles does not merge prices. Recovery
              replaces the code with a new one.
            </Trans>
          </p>
          <form
            className="access-form"
            onSubmit={(event) => {
              void recover(event);
            }}
          >
            <Field
              label={t`Recovery code`}
              name="code"
              required
              maxLength={80}
              autoComplete="off"
              spellCheck={false}
            />
            <Field
              label={t`This device’s name`}
              name="deviceName"
              required
              maxLength={60}
              defaultValue={defaultDeviceName()}
            />
            {error && <Notice>{error}</Notice>}
            <Button busy={busy} type="submit">
              <Trans>Recover profile</Trans>
            </Button>
          </form>
          <p className="access-alternative">
            <Link to="/connect">
              <Trans>Connect using another device instead</Trans>
            </Link>
          </p>
        </>
      )}
    </AccessPage>
  );
}
